version: "3"
services:
  api:
    container_name: ${PREFIX}_api
    build:
      context: ./api
      args:
        ENV: local
    volumes:
      - ./src:/go/src/github.com/IkezoeMakoto/short-url/api/src
#    links:
#      - database
#      - redis
    ports:
      - "${API_PORT}:8080"