version: "3"
services:
  api:
    container_name: ${PREFIX}_api
    build:
      context: ./api
      args:
        ENV: local
    volumes:
      - ./src:/go/src/github.com/IkezoeMakoto/short-url/api/src
    links:
      - redis
    ports:
      - "${API_PORT}:8080"

  redis:
    container_name: ${PREFIX}_redis
    image: redis:4.0-alpine